# Generated by Django 2.2.6 on 2020-07-15 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20200623_1243'),
        ('devices', '0002_devicevalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceReading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aggregated_power', models.FloatField(null=True)),
                ('phase_1_power', models.FloatField(null=True)),
                ('phase_2_power', models.FloatField(null=True)),
                ('phase_3_power', models.FloatField(null=True)),
                ('aggregated_current', models.FloatField(null=True)),
                ('phase_1_current', models.FloatField(null=True)),
                ('phase_2_current', models.FloatField(null=True)),
                ('phase_3_current', models.FloatField(null=True)),
                ('timestamp', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceWork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('work_type', models.CharField(choices=[('01', 'Maintenance'), ('02', 'Install'), ('NA', 'Not Available')], default='NA', max_length=2)),
                ('proposed_datetime', models.DateTimeField(null=True)),
                ('executed_datetime', models.DateTimeField(null=True)),
                ('remarks', models.CharField(max_length=255, null=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
            ],
        ),
        migrations.DeleteModel(
            name='DeviceValue',
        ),
        migrations.AddField(
            model_name='device',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Account'),
        ),
        migrations.AddField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('01', 'Bolt v1.0'), ('NA', 'Not Available')], default='NA', max_length=2),
        ),
        migrations.AddField(
            model_name='devicework',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.Device'),
        ),
        migrations.AddField(
            model_name='devicework',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='devicereading',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.Device'),
        ),
    ]
