apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    name: zeus-webapp
  name: zeus-webapp
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  selector:
    matchLabels:
      app: zeus-webapp
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: zeus-webapp
    spec:
      containers:
      - image: syafiqpipe/zeus-webapp:latest
        imagePullPolicy: Always   
        name: zeus-webapp
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30