# Generated by Django 2.2.6 on 2020-06-23 12:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=255)),
                ('created', models.BooleanField(default=True)),
                ('sent', models.BooleanField(default=False)),
                ('read', models.BooleanField(default=False)),
            ],
        ),
    ]
