# Generated by Django 2.2.6 on 2020-06-23 12:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aimodel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('version', models.CharField(blank=True, default='0.0.1', max_length=255)),
                ('purpose', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('aimodel_type', models.CharField(choices=[('NA', 'Not Available')], default='NA', max_length=2)),
            ],
        ),
    ]
