# Generated by Django 2.2.6 on 2020-06-23 12:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
            ],
        ),
        migrations.CreateModel(
            name='ApplianceBase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('brand', models.CharField(max_length=255, null=True)),
                ('model', models.CharField(max_length=255, null=True)),
                ('year', models.CharField(max_length=255, null=True)),
                ('manufacturer', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApplianceTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_datetime', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('NA', 'Not Available')], default='NA', max_length=2)),
                ('appliance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appliances.Appliance')),
            ],
        ),
        migrations.AddField(
            model_name='appliance',
            name='appliance_base',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appliances.ApplianceBase'),
        ),
        migrations.AddField(
            model_name='appliance',
            name='building',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='buildings.Building'),
        ),
    ]
