# Generated by Django 2.2.6 on 2020-07-15 12:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appliancetransaction',
            old_name='transaction_datetime',
            new_name='at_datetime',
        ),
        migrations.RemoveField(
            model_name='appliancetransaction',
            name='status',
        ),
        migrations.AddField(
            model_name='appliance',
            name='install_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='appliance',
            name='purchase_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='appliance',
            name='serial_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appliancebase',
            name='batch_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appliancebase',
            name='group',
            field=models.CharField(choices=[('NA', 'Not Available')], default='NA', max_length=2),
        ),
        migrations.AddField(
            model_name='appliancetransaction',
            name='real_cumulative_delta_end_range',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='appliancetransaction',
            name='real_cumulative_delta_start_range',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='appliancetransaction',
            name='real_delta_end_range',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='appliancetransaction',
            name='real_delta_start_range',
            field=models.FloatField(null=True),
        ),
        migrations.CreateModel(
            name='ApplianceTransactionMode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('at_state', models.CharField(choices=[('ON', 'On'), ('OF', 'Off'), ('NA', 'Not Available')], default='NA', max_length=2)),
                ('at_mode', models.CharField(choices=[('ON', 'On'), ('OF', 'Off'), ('NA', 'Not Available')], default='NA', max_length=2)),
                ('estimated_delta_start_range', models.FloatField(null=True)),
                ('estimated_delta_end_range', models.FloatField(null=True)),
                ('estimated_cumulative_delta_start_range', models.FloatField(null=True)),
                ('estimated_cumulative_delta_end_range', models.FloatField(null=True)),
                ('appliance_base', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appliances.ApplianceBase')),
            ],
        ),
        migrations.AddField(
            model_name='appliancetransaction',
            name='appliance_transaction_mode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appliances.ApplianceTransactionMode'),
        ),
    ]
