# Generated by Django 2.2.6 on 2020-07-15 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0003_appliance_at_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliancetransaction',
            name='at_state',
            field=models.CharField(choices=[('ON', 'On'), ('OF', 'Off'), ('NA', 'Not Available')], default='NA', max_length=2),
        ),
    ]
