# Generated by Django 2.2.6 on 2020-07-15 22:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0004_appliancetransaction_at_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplianceActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('at_state', models.CharField(choices=[('ON', 'On'), ('OF', 'Off'), ('NA', 'Not Available')], default='NA', max_length=2)),
                ('appliance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appliances.Appliance')),
            ],
        ),
    ]
