# Generated by Django 2.2.6 on 2020-07-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mobile_number',
            field=models.IntegerField(null=True),
        ),
    ]
