# Generated by Django 2.2.6 on 2020-09-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='identification_number',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
