# Generated by Django 2.2.6 on 2020-06-23 12:43

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('account_number', models.CharField(blank=True, max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('account_created', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
