# Generated by Django 2.2.6 on 2020-06-23 12:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('solved', models.BooleanField(default=False)),
                ('ticket_type', models.CharField(choices=[('AR', 'Architect'), ('AN', 'Analyst'), ('DV', 'Developer'), ('NA', 'Not Available')], default='NA', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField(default='NA')),
                ('sent', models.BooleanField(default=False)),
                ('received', models.BooleanField(default=False)),
                ('read', models.BooleanField(default=False)),
                ('sent_datetime', models.DateTimeField(null=True)),
                ('received_datetime', models.DateTimeField(null=True)),
                ('read_datetime', models.DateTimeField(null=True)),
            ],
        ),
    ]
